version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  mongo-user-service:
    image: mongo:6
    container_name: mongo-user-service
    ports:
      - "27017:27017"
    env_file:
      - ./user/.env
    volumes:
      - mongo-user-data:/data/db

  mongo-club-service:
    image: mongo:6
    container_name: mongo-club-service
    ports:
      - "27018:27017"
    env_file:
      - ./club/.env
    volumes:
      - mongo-club-data:/data/db

  mongo-library-service:
    image: mongo:6
    container_name: mongo-library-service
    ports:
      - "27019:27017"
    env_file:
      - ./library/.env
    volumes:
      - mongo-library-data:/data/db

  mongo-book-service:
    image: mongo:6
    container_name: mongo-book-service
    ports:
      - "27020:27017"
    env_file:
      - ./book/.env
    volumes:
      - mongo-book-data:/data/db

  mongo-chat-service:
    image: mongo:6
    container_name: mongo-chat-service
    ports:
      - "27021:27017"
    env_file:
      - ./chat/.env
    volumes:
      - mongo-chat-data:/data/db

volumes:
  mongo-user-data:
  mongo-club-data:
  mongo-library-data:
  mongo-book-data:
  mongo-chat-data:
